"""upgrade logic timezone

Revision ID: 3f0d370d0236
Revises: b510a2aa4465
Create Date: 2024-04-02 15:51:20.101657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f0d370d0236'
down_revision: Union[str, None] = 'b510a2aa4465'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toptions', sa.Column('timezone_server', sa.Integer(), nullable=True))
    op.add_column('toptions', sa.Column('timezone_admin', sa.Integer(), nullable=True))
    op.drop_column('toptions', 'timezone')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toptions', sa.Column('timezone', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('toptions', 'timezone_admin')
    op.drop_column('toptions', 'timezone_server')
    # ### end Alembic commands ###
