"""empty message

Revision ID: 56084b6d02c0
Revises: cae67cb60b6b
Create Date: 2024-03-10 14:40:52.452432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56084b6d02c0'
down_revision: Union[str, None] = 'cae67cb60b6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tclient', sa.Column('username', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tclient', 'username')
    # ### end Alembic commands ###
