"""empty message

Revision ID: 69b770463d6e
Revises: 
Create Date: 2024-03-28 16:36:21.791281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69b770463d6e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tclient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('middle_name', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('username', sa.String(length=60), nullable=True),
    sa.Column('telegram_id', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('tday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('begin_time', sa.Time(timezone=True), nullable=False),
    sa.Column('end_time', sa.Time(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin_time', sa.Time(timezone=True), nullable=False),
    sa.Column('end_time', sa.Time(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('towner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('middle_name', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.Column('token', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.create_table('tservice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=60), nullable=False),
    sa.Column('cost', sa.Integer(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('after_pause', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tevent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_day', sa.Integer(), nullable=False),
    sa.Column('id_service', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=60), nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['tclient.id'], ),
    sa.ForeignKeyConstraint(['id_day'], ['tday.id'], ),
    sa.ForeignKeyConstraint(['id_service'], ['tservice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('toptions_client',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('is_notification', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['tclient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=60), nullable=True),
    sa.ForeignKeyConstraint(['id_client'], ['tclient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('treports')
    op.drop_table('toptions_client')
    op.drop_table('tevent')
    op.drop_table('tservice')
    op.drop_table('towner')
    op.drop_table('toptions')
    op.drop_table('tday')
    op.drop_table('tclient')
    # ### end Alembic commands ###
