"""delete timezone

Revision ID: b510a2aa4465
Revises: db429c4594e1
Create Date: 2024-04-02 14:53:13.608800

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b510a2aa4465'
down_revision: Union[str, None] = 'db429c4594e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tday', 'begin_time',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('tday', 'end_time',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('tevent', 'time',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('toptions', 'begin_time',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.Time(),
               existing_nullable=False)
    op.alter_column('toptions', 'end_time',
               existing_type=postgresql.TIME(timezone=True),
               type_=sa.Time(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('toptions', 'end_time',
               existing_type=sa.Time(),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=False)
    op.alter_column('toptions', 'begin_time',
               existing_type=sa.Time(),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=False)
    op.alter_column('tevent', 'time',
               existing_type=sa.Time(),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=False)
    op.alter_column('tday', 'end_time',
               existing_type=sa.Time(),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=False)
    op.alter_column('tday', 'begin_time',
               existing_type=sa.Time(),
               type_=postgresql.TIME(timezone=True),
               existing_nullable=False)
    # ### end Alembic commands ###
