"""token

Revision ID: cae67cb60b6b
Revises: c86c9d941930
Create Date: 2024-03-09 13:43:20.411192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cae67cb60b6b'
down_revision: Union[str, None] = 'c86c9d941930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('towner', sa.Column('token', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('towner', 'token')
    # ### end Alembic commands ###
