"""empty message

Revision ID: d77a4adad5d3
Revises: 86b663100371
Create Date: 2024-03-14 14:11:55.091876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd77a4adad5d3'
down_revision: Union[str, None] = '86b663100371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tclient', sa.Column('telegram_id', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tclient', 'telegram_id')
    # ### end Alembic commands ###
