"""create option timezone

Revision ID: db429c4594e1
Revises: 20c973321d81
Create Date: 2024-04-02 14:50:23.346161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db429c4594e1'
down_revision: Union[str, None] = '20c973321d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('toptions', sa.Column('timezone', sa.Integer(), nullable=True))
    op.add_column('toptions_client', sa.Column('timezone', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('toptions_client', 'timezone')
    op.drop_column('toptions', 'timezone')
    # ### end Alembic commands ###
