"""add_unique_phone

Revision ID: e25971af7059
Revises: e6d91d327550
Create Date: 2024-03-06 13:41:50.759369

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e25971af7059'
down_revision: Union[str, None] = 'e6d91d327550'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tclient', ['phone'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tclient', type_='unique')
    # ### end Alembic commands ###
