"""create owner and options

Revision ID: ee19fed57dc1
Revises: e25971af7059
Create Date: 2024-03-07 21:29:54.873764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee19fed57dc1'
down_revision: Union[str, None] = 'e25971af7059'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('toptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('begin_time', sa.DateTime(), nullable=False),
    sa.Column('end_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('towner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=60), nullable=False),
    sa.Column('first_name', sa.String(length=60), nullable=False),
    sa.Column('middle_name', sa.String(length=60), nullable=False),
    sa.Column('phone', sa.String(length=60), nullable=False),
    sa.Column('password', sa.String(length=60), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone')
    )
    op.drop_column('tclient', 'token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tclient', sa.Column('token', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('towner')
    op.drop_table('toptions')
    # ### end Alembic commands ###
