"""empty message

Revision ID: f3c6468f4c83
Revises: dfbaeae71627
Create Date: 2024-03-11 21:12:26.788451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c6468f4c83'
down_revision: Union[str, None] = 'dfbaeae71627'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('treports', sa.Column('text', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('treports', 'text')
    # ### end Alembic commands ###
